name: Code Coverage with JaCoCo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Compile the project
        run: mvn install -DskipTests
      - name: Test the project and create coverage report
        run: mvn test
